### ISSUE TITLE
Members of support should be in strict alphabetical order.

### ISSUE THREAD

**Issue by jpmedley** [kaycebasques/mdncrawler#1]
For a while now, `webview_android` was listed at the top because it was originally named `android`. New PRs now put it at the bottom and this will soon be forced.

**Comment by kaycebasques** [comment]
Sorry Joe, I must not have configured email notifications correctly on this repo, because I'm just seeing your issues now.

I think the little hack that I just pushed should fix this

**Comment by kaycebasques** [comment]
Hmm, maybe not...

**Comment by kaycebasques** [comment]
OK, now it's fixed
