### ISSUE TITLE
Output should contain webview_android instead of android

### ISSUE THREAD

**Issue by jpmedley** [kaycebasques/mdncrawler#2]
When I started working on MDN it wasn't clear that the browser referred to as 'Android' was the Android Webview. I've been trying to change this, but it still appears in a few places. This means that you might find interfaces where some members say `android` and others say `webview_android`. These should be regarded as the same browser and output as `webview_android`.

**Comment by kaycebasques** [comment]
OK, I haven't encountered that yet, but I'll update the script if I do
